services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./dev.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: